---
title: "Untitled"
author: "Gustavo Reyes"
date: '2022-10-09'
output: html_document
---

```{r}
library(tidyverse)
library(scales)
library(forcats)
```
# Power Analysis
Reading in the data
```{r}
Powers<-read.csv("Data_Tomato_Outputs/Powers_Out11.csv")
```

```{r}
Powers$Mass<-as.factor(Powers$Mass)
Powers$variable<-as.factor(Powers$variable)
Powers$Type<-as.factor(Powers$Type)

Powers$Type<-factor(Powers$Type,levels=c("Preharvest", "Harvest", "Receiving", "Packed Product"))
Powers$Mass<-factor(Powers$Mass,levels=c("2 Tomatoes", "6 Tomatoes", "20 Tomatoes", "60 Tomatoes","20 Tomato Mash", "60 Tomato Mash"))
Powers$Cont<-factor(Powers$Cont,levels=c("100%", "10%", "1%", "0.1%"))
```

```{r}
Powers_Summary = Powers %>% 
  group_by(Type, Mass, variable, Cont) %>% 
  #summarise(mean = median(value), CI_95 = mean + margin_calc(value),CI_05 = mean - margin_calc(value))
  summarise(mean = median(value), CI_95 = quantile(value, 0.90),CI_05 = quantile(value, 0.1)) 

Powers_Summary$Cont<-factor(Powers_Summary$Cont,levels=c("100%", "10%", "1%", "0.1%"))

Powers_Summary %>% 
ggplot(aes(x = Type, y = mean, color = Mass,shape = variable ,group = interaction(Mass, variable)))+
  #geom_point(stroke = 4,position = position_dodge(0.3))+
  #geom_line(aes(linetype= variable),size = 0.3,position = position_dodge(0.3))+
  geom_pointrange(aes(ymin=CI_05, ymax=CI_95),position = position_dodge(0.6), size = 0.6)+
  geom_errorbar(aes(ymin=CI_05, ymax=CI_95),width = 0.5, size =0.5,position = position_dodge(0.6))+
  ylab("Sampling Plan Power")+
  xlab("Sampling at Process Step")+
  #scale_size_manual(name = "Tomatoes Sampled")+
  scale_color_discrete(name="Sampling Plan Mass")+
  scale_shape_discrete(name="Pick Number",labels = c("Power_Pick_1" ="Pick 1", "Power_Pick_2" ="Pick 2", "Power_Pick_3" ="Pick 3") )+
  scale_linetype_discrete(name="Pick Number",labels = c("Power_Pick_1" ="Pick 1", "Power_Pick_2" ="Pick 2", "Power_Pick_3" ="Pick 3"))+
  facet_wrap(~Cont,nrow = 2)+
  theme_bw()

#Boxplot
Powers%>% 
ggplot(aes(x = Type, y = value, color = Mass, fill = Mass))+
#geom_point(position=position_jitterdodge(), alpha = 0.3, size = 1)+
geom_boxplot(alpha = 0.5, outlier.shape=NA)+
  scale_color_discrete(name="Sampling Plan Mass")+
  scale_fill_discrete(name="Sampling Plan Mass")+
  ylab("Sampling Plan Power")+
  xlab("Sampling at Process Step")+
  facet_wrap(~Cont, nrow =2)+
  theme_bw()

ggsave(filename="Plot Outputs/Powers1011.tiff",width = 25, height = 15, units = "cm", dpi = 600)

```

#Contamination at sampling point

```{r}
Cont_Prog<-read.csv("Data_Tomato_Outputs/SampPoint11.csv")

Cont_Prog$Type[Cont_Prog$Type == "PH"] <- "Preharvest"
Cont_Prog$Type[Cont_Prog$Type == "H"] <- "Harvest"
Cont_Prog$Type[Cont_Prog$Type == "R"] <- "Receiving"
Cont_Prog$Type[Cont_Prog$Type == "PP"] <- "Packed Product"

Cont_Prog$Type<-as.factor(Cont_Prog$Type)
Cont_Prog$Pick<-as.factor(Cont_Prog$Pick)

Cont_Prog$Type<-factor(Cont_Prog$Type,levels=c("Preharvest", "Harvest", "Receiving", "Packed Product"))

Cont_Prog$`Cont.Type`<-factor(Cont_Prog$`Cont.Type`,levels=c("100%", "10%", "1%", "0.1%"))

Cont_Prog %>% 
ggplot(aes(x = Type, y = Cont,color = Pick))+
#geom_point(position=position_jitterdodge(), alpha = 0.3, size = 1)+
geom_boxplot()+
xlab("Sampling Plan")+ ylab ("Total Adulteran Cells (TAC) at sampling point")+
facet_wrap(~`Cont.Type`)+
scale_y_continuous(labels = scales::comma)+
  theme_bw()

```

#Prevalence at sampling point

```{r}
Cont_Prog<-read.csv("Data_Tomato_Outputs/PrevSampPoint11.csv")

Cont_Prog$Type[Cont_Prog$Type == "PH"] <- "Preharvest"
Cont_Prog$Type[Cont_Prog$Type == "H"] <- "Harvest"
Cont_Prog$Type[Cont_Prog$Type == "R"] <- "Receiving"
Cont_Prog$Type[Cont_Prog$Type == "PP"] <- "Packed Product"

Cont_Prog$Type<-as.factor(Cont_Prog$Type)
Cont_Prog$Pick<-as.factor(Cont_Prog$Pick)

Cont_Prog$Type<-factor(Cont_Prog$Type,levels=c("Preharvest", "Harvest", "Receiving", "Packed Product"))

Cont_Prog$`Cont.Type`<-factor(Cont_Prog$`Cont.Type`,levels=c("100%", "10%", "1%", "0.1%"))


Cont_Prog %>% 
ggplot(aes(x = Type, y = Cont,color = Pick))+
#geom_point(position=position_jitterdodge(), alpha = 0.3, size = 1)+
geom_boxplot()+
xlab("Sampling Plan")+ ylab ("Total Adulteran Cells (TAC) at sampling point")+
facet_wrap(~`Cont.Type`, scales = "free_y")+
scale_y_continuous(labels = scales::comma)+
  theme_bw()

```

#Consumer Exposure
```{r}
Exps_all<-read.csv("Data_Tomato_Outputs/Exps11.csv")

Exps_all$Mass<-factor(Exps_all$Mass,levels=c("Baseline","2 Tomatoes", "6 Tomatoes", "20 Tomatoes", "60 Tomatoes","20 Tomato Mash", "60 Tomato Mash"))

Exps_all$Cont<-factor(Exps_all$Cont,levels=c("100%", "10%", "1%", "0.1%"))

Exps_all$Type<-factor(Exps_all$Type,levels=c("Baseline","Preharvest", "Harvest", "Receiving", "Packed Product"))



Exps_all %>% 
  ggplot(aes(x = Type, y = Total_CFU, fill = Mass))+
  geom_col(position = position_dodge())+
  facet_wrap(~Cont)+
  scale_y_continuous(labels = scales::comma)+
  ylab("Total CFU that reached the consumer")+
  xlab("Sampling Location")+
  theme_bw()

ggsave(filename="Plot Outputs/Exps1011.tiff",width = 25, height = 15, units = "cm", dpi = 600)

```

#Relative Exposure
```{r}
Exps_all$Cont<-factor(Exps_all$Cont,levels=c("Baseline", "100%", "10%", "1%", "0.1%"))
Exps_all$Type<-factor(Exps_all $Type,levels=c("Baseline","Preharvest", "Harvest", "Receiving", "Packed Product"))

Exps_RE<-Exps_all %>% 
  group_by(Cont) %>% 
  summarize(RE = Total_CFU/Total_CFU[Type=="Baseline"])

Exps_RE<-Exps_all %>% 
  select(Mass, Type, Total_CFU) %>% 
  bind_cols(Exps_RE)

Exps_RE$Type<-factor(Exps_RE$Type,levels=c("Baseline","Preharvest", "Harvest", "Receiving", "Packed Product"))

Exps_RE %>% 
  ggplot(aes(x = Type, y = RE, shape = Mass, color = Mass))+
  #geom_col(position = position_dodge())+
  geom_point(position = position_dodge(width = 0.6), size =3)+
  #coord_flip()+
  facet_wrap(~Cont)+
  xlab("Sampling Location")+
  ylab("Relative Exposure")+
  theme_bw()+
  scale_shape_manual(values = c(4,8,15,16,17,18,21)) 

ggsave(filename="Plot Outputs/REExps1011.tiff",width = 25, height = 15, units = "cm", dpi = 600)

```


#Factor Sensitivity
log10(Scenario/Baseline)

```{r}
Exps_all$Cont<-factor(Exps_all$Cont,levels=c("Baseline", "100%", "10%", "1%", "0.1%"))
Exps_all$Type<-factor(Exps_all $Type,levels=c("Baseline","Preharvest", "Harvest", "Receiving", "Packed Product"))

Exps_FS<-Exps_all %>% 
  group_by(Cont) %>% 
  summarize(FS = log10(Total_CFU/Total_CFU[Type=="Baseline"]))

Exps_Other<-Exps_all %>% 
  select(Mass, Type, Total_CFU) %>% 
  bind_cols(Exps_FS)

Exps_Other$Type<-factor(Exps_Other$Type,levels=c("Baseline","Preharvest", "Harvest", "Receiving", "Packed Product"))

Exps_Other %>% 
  ggplot(aes(x = Type, y = FS, fill = Mass))+
  geom_col(position = position_dodge())+
  coord_flip()+
  geom_hline(yintercept = -1.69,linetype="dashed", 
                color = "black", size=1)+
  facet_wrap(~Cont)+
  xlab("Sampling Location")+
  ylab("Factor Senstivity FS | log10 (Scenario/Baseline)")+
  theme_bw()

ggsave(filename="Plot Outputs/FS1011.tiff",width = 25, height = 15, units = "cm", dpi = 600)

Exps_Other %>% 
  ggplot(aes(x = Type, y = FS, fill = Mass))+
  geom_col(position = position_dodge())+
  coord_flip()+
  geom_hline(yintercept = -1.69,linetype="dashed", 
                color = "black", size=1)+
  facet_wrap(~Cont, scales = "free_y")+
  xlab("Sampling Location")+
  ylab("Factor Senstivity FS | log10 (Scenario/Baseline)")+
  theme_bw()


```
#PP

Protective Power

```{r}
PP<-read.csv("Data_Tomato_Outputs/PP10.csv")
PP2<-read.csv("Data_Tomato_Outputs/PP210.csv")

Get_PP_df<-function(PP2){
  R1<-PP2 %>% 
    filter(X1 == "No") %>% 
    group_by(X6) %>% 
    summarize(total =sum(X0)) %>% 
    mutate(class= "Total Rejected")
  T1<-PP2 %>% 
    filter(X1 == "No") %>% 
    group_by(X6) %>% 
    summarize(total =sum(CFU_Bef_Pick1PHS),Prot_Rate = sum(X0)/sum(CFU_Bef_Pick1PHS)) %>% 
    mutate(class= "Total Available") 
  
  TR1<-T1%>%
    bind_rows(R1) %>% 
    mutate(Pick = "PH sampling Pick 1")
  
  
  R2<-PP2 %>% 
  filter(X3 == "No") %>% 
  group_by(X6) %>% 
  summarize(total =sum(X2))%>% 
  mutate(class= "Total Rejected")
  
  T2<-PP2 %>% 
  filter(X3 == "No") %>% 
  group_by(X6) %>% 
    summarize(total =sum(CFU_Bef_Pick2PHS),Prot_Rate = sum(X2)/sum(CFU_Bef_Pick2PHS)) %>% 
  mutate(class= "Total Available")
  
  TR2<-T2%>%
  bind_rows(R2) %>%
  mutate(Pick = "PH sampling Pick 2")
  
  
  
  R3<-PP2 %>% 
  filter(X5 == "No") %>% 
  group_by(X6) %>% 
  summarize(total =sum(X4))%>% 
  mutate(class= "Total Rejected")
  
  T3<-PP2 %>% 
  filter(X5 == "No") %>% 
  group_by(X6) %>% 
  summarize(total =sum(CFU_Bef_Pick3PHS),Prot_Rate = sum(X4)/sum(CFU_Bef_Pick3PHS)) %>% 
  mutate(class= "Total Available")
  
  TR3<-T3%>%
  bind_rows(R3) %>%
  mutate(Pick = "PH sampling Pick 3") 
  
  TR_Tog<-rbind(TR1,TR2,TR3)
  return (TR_Tog)
}


TR20T<-Get_PP_df(PP2= PP2)
TR20T$Sampling<-"20 Tomatoes"
TR2T<-Get_PP_df(PP2= PP)
TR2T$Sampling<-"2 Tomatoes"

TR_All<-rbind(TR20T,TR2T)

TR_All%>% 
ggplot()+
geom_col(aes(x = X6, y = total,fill = class),position = position_identity(), alpha = 0.9)+
geom_point(aes(x = X6, y =Prot_Rate*2000000), alpha = 0.5, size = 1)+
geom_smooth(aes(x = X6, y =Prot_Rate*2000000), alpha = 0.1,span = 0.3, size = 0.7)+
scale_y_continuous(labels = scales::comma,sec.axis = sec_axis(~./2000000, name = 'Protection Power'))+
  xlab("Day where contamination event happened")+
  ylab("Tota Adulterant Cells (TAC)")+
  facet_grid(Sampling~Pick, scales = "free_x")+
  scale_fill_discrete("Contamination Outcome")

ggsave(filename="Plot Outputs/PP0101.tiff",width = 30, height = 20, units = "cm", dpi = 600)





```

