---
title: "Tomato Analysis Variable"
output: html_document
date: '2022-09-20'
---

```{r}
library(tidyverse)
library(scales)
library(forcats)
```
# Power Analysis

Reading in the data
```{r}
Powers<-read.csv("Data_Tomato_Outputs/Powers_Out1.csv")
Powers_PS<-read.csv("Data_Tomato_Outputs/Powers_Out_PS1.csv")
```

```{r}
Powers$ContType<-"Uniform"
Powers_PS$ContType<-"PointSource"

Powers<-rbind(Powers,Powers_PS)

Powers$Mass<-as.factor(Powers$Mass)
Powers$variable<-as.factor(Powers$variable)
Powers$Type<-as.factor(Powers$Type)

Powers$Type<-factor(Powers$Type,levels=c("Preharvest", "Harvest", "Receiving", "Packed Product"))
Powers$Mass<-factor(Powers$Mass,levels=c("2 tomatoes", "6 tomatoes", "20 x 5 tomatoes"))
Powers$ContType<-factor(Powers$ContType,levels=c("Uniform", "PointSource"))
#Power_data$Samp_Plan<-factor(Power_data$Samp_Plan,levels=c("Preharvest", "Harvest", "Receiving", "Packed Product"))
#Power_data$`Cont Type`<-factor(Power_data$`Cont Type`,levels=c("Uniform", "0.1% Cluster"))
#Power_data$Samp_Mass<-as.factor(Power_data$Samp_Mass)
margin_calc<-function(x){
  margin <- qt(0.975,df=50-1)*sd(x)/sqrt(50)
}


Powers_Summary = Powers %>% 
  group_by(Type, Mass, variable, ContType) %>% 
  #summarise(mean = median(value), CI_95 = mean + margin_calc(value),CI_05 = mean - margin_calc(value))
  summarise(mean = mean(value), CI_95 = quantile(value, 0.90),CI_05 = quantile(value, 0.1)) 
write.csv(Powers_Summary, file = "Data_Tomato_Outputs/Powers_Summary.csv")

Powers_Summary=read.csv("Data_Tomato_Outputs/Powers_Summary.csv")
Powers_Summary$Mass<-as.factor(Powers_Summary$Mass)
Powers_Summary$variable<-as.factor(Powers_Summary$variable)
Powers_Summary$Type<-as.factor(Powers_Summary$Type)

Powers_Summary$Type<-factor(Powers_Summary$Type,levels=c("Preharvest", "Harvest", "Receiving", "Packed Product"))
Powers_Summary$Mass<-factor(Powers_Summary$Mass,levels=c("2 tomatoes", "6 tomatoes", "20 x 5 tomatoes"))
Powers_Summary$ContType<-factor(Powers_Summary$ContType,levels=c("Uniform", "PointSource"))

Powers_Summary %>% 
ggplot(aes(x = Type, y = mean, color = Mass,shape = variable ,group = interaction(Mass, variable)))+
  #geom_point(stroke = 4,position = position_dodge(0.3))+
  #geom_line(aes(linetype= variable),size = 0.3,position = position_dodge(0.3))+
  geom_pointrange(aes(ymin=CI_05, ymax=CI_95),position = position_dodge(0.6), size = 0.6)+
  geom_errorbar(aes(ymin=CI_05, ymax=CI_95),width = 0.5, size =0.5,position = position_dodge(0.6))+
  ylab("Sampling Plan Power")+
  xlab("Sampling at Process Step")+
  #scale_size_manual(name = "Tomatoes Sampled")+
  scale_color_discrete(name="Sampling Plan Mass")+
  scale_shape_discrete(name="Pick Number",labels = c("Power_Pick_1" ="Pick 1", "Power_Pick_2" ="Pick 2", "Power_Pick_3" ="Pick 3") )+
  scale_linetype_discrete(name="Pick Number",labels = c("Power_Pick_1" ="Pick 1", "Power_Pick_2" ="Pick 2", "Power_Pick_3" ="Pick 3"))+
  facet_grid(~ContType)+
  theme_bw()

ggsave(filename=  "Plot Outputs/Powers925.png",width = 25, height = 15, units = "cm", dpi = 600)


Powers%>% 
ggplot(aes(x = Type, y = value, color = Mass))+
geom_point(position=position_jitterdodge(), alpha = 0.3, size = 1)+
geom_boxplot(alpha = 0.5, outlier.shape=NA, size = 1)+
  scale_color_discrete(name="Sampling Plan Mass")+
  ylab("Sampling Plan Power")+
  xlab("Sampling at Process Step")+
  facet_wrap(~ContType)+
  theme_bw()

Powers%>% 
ggplot(aes(x = Type, y = value, color = Mass))+
geom_point(position=position_jitterdodge(), alpha = 0.3, size = 1)+
geom_boxplot(alpha = 0.5, outlier.shape=NA, size = 1)+
facet_grid(~variable, labeller = labeller(variable = c("Power_Pick_1" ="Pick 1", "Power_Pick_2" ="Pick 2", "Power_Pick_3" ="Pick 3")))+
  ylab("Sampling Plan Power")+
  xlab("Sampling Plan")+
  scale_color_discrete(name="Sampling Plan Mass")+
  theme_bw()

+
  scale_shape_manual(values = c(15,16,17),name = "Pick")+
  scale_size_manual(values=c(1,1.5,2), name = "Tomatoes Sampled")+
  xlab("Sampling Plan Location")+ ylab ("Sampling Plan Power")+
  scale_y_continuous(n.breaks = 10,labels = scales::percent_format(accuracy = 1))+
  facet_grid(~`Cont Type`)

```
#Contmaination at sampling point

```{r}
Cont_Prog<-read.csv("Data_Tomato_Outputs/Contam_Samp_Out1.csv")
Cont_Prog_PS<-read.csv("Data_Tomato_Outputs/Contam_Samp_Out_PS1.csv")

Cont_Prog$ContType<-"Uniform"
Cont_Prog_PS$ContType<-"Point Source"

Cont_Prog<-rbind(Cont_Prog, Cont_Prog_PS)

Cont_Prog$Type[Cont_Prog$Type == "PH"] <- "Preharvest"
Cont_Prog$Type[Cont_Prog$Type == "H"] <- "Harvest"
Cont_Prog$Type[Cont_Prog$Type == "RS"] <- "Receiving"
Cont_Prog$Type[Cont_Prog$Type == "PPS"] <- "Packed Product"

```

```{r}
#Cont_Prog$Mass<-factor(Cont_Prog$Mass,levels=c("2 tomatoes", "6 tomatoes", "20 x 5 tomatoes"))
Cont_Prog$Type<-as.factor(Cont_Prog$Type)
Cont_Prog$Pick<-as.factor(Cont_Prog$Pick)

Cont_Prog$Type<-factor(Cont_Prog$Type,levels=c("Preharvest", "Harvest", "Receiving", "Packed Product"))

Cont_Prog %>% 
  group_by(Type,Pick) %>% 
  summarise(max(Cont))

Cont_Prog %>% 
ggplot(aes(x = Type, y = Cont,color = Pick))+
#geom_point(position=position_jitterdodge(), alpha = 0.3, size = 1)+
geom_boxplot()+
xlab("Sampling Plan")+ ylab ("Total Adulteran Cells (TAC) at sampling point")+
facet_wrap(~`ContType`)+
scale_y_continuous(labels = scales::comma)

ggsave(filename=  "Plot Outputs/Cont_Sampling_Point1.png",width = 25, height = 15, units = "cm", dpi = 600)
```
# Contmaination Spread

```{r}
Prev_Prog<-read.csv("Data_Tomato_Outputs/Prev_Samp_Out1.csv")
Prev_Prog_PS<-read.csv("Data_Tomato_Outputs/Prev_Samp_Out_PS1.csv")

Prev_Prog$PrevType<-"Uniform"
Prev_Prog_PS$PrevType<-"Point Source"

Prev_Prog<-rbind(Prev_Prog, Prev_Prog_PS)

Prev_Prog$Type[Prev_Prog$Type == "PH"] <- "Preharvest"
Prev_Prog$Type[Prev_Prog$Type == "H"] <- "Harvest"
Prev_Prog$Type[Prev_Prog$Type == "RS"] <- "Receiving"
Prev_Prog$Type[Prev_Prog$Type == "PPS"] <- "Packed Product"

```

```{r}
#Prev_Prog$Mass<-factor(Prev_Prog$Mass,levels=c("2 tomatoes", "6 tomatoes", "20 x 5 tomatoes"))
Prev_Prog$Type<-as.factor(Prev_Prog$Type)
Prev_Prog$Pick<-as.factor(Prev_Prog$Pick)

Prev_Prog$Type<-factor(Prev_Prog$Type,levels=c("Preharvest", "Harvest", "Receiving", "Packed Product"))


Prev_Prog %>% 
ggplot(aes(x = Type, y = Cont,color = Pick))+
#geom_point(position=position_jitterdodge(), alpha = 0.3, size = 1)+
geom_boxplot()+
xlab("Sampling Plan")+ ylab ("Prevalence of contmaination at each sampling point")+
facet_wrap(~`PrevType`,scales="free_y")+
scale_y_continuous(labels = scales::percent )

ggsave(filename=  "Plot Outputs/Prev_Sampling_Point1.png",width = 25, height = 15, units = "cm", dpi = 600)
```
#Exposure. 
```{r}
Exps<-read.csv("Data_Tomato_Outputs/Exps.csv")
ExpsPS<-read.csv("Data_Tomato_Outputs/ExpsPS.csv")

Exps<-rbind(Exps, ExpsPS)

Exps %>%
  filter(ContType == "Uniform") %>% 
  group_by(Type, ContType) %>% 
  summarise(median =sum(X42), CI_95 = max(X42),CI_05 = quantile(X42, 0.1)) %>% 
  mutate(FS = log10(median/2504775)) %>% 
  ggplot(aes(x = fct_reorder(Type, abs(FS)), y = FS))+
  geom_col()+
  coord_flip()

Exps %>%
  filter(ContType == "Point Source") %>% 
  group_by(Type, ContType) %>% 
  summarise(median =sum(X42), CI_95 = max(X42),CI_05 = quantile(X42, 0.1)) %>% 
  mutate(FS = log10(median/2662890)) %>% 
  ggplot(aes(x = fct_reorder(Type, abs(FS)), y = FS))+
  geom_col()+
  coord_flip()



Exps %>%
  filter(ContType == "Uniform") %>% 
  group_by(Type, ContType) %>% 
  ggplot(aes(x = Type, y = X42))+
  geom_boxplot()



```


```{r}
Exps_U<-read.csv("Data_Tomato_Outputs/Exps_U.csv")
Exps_PS<-read.csv("Data_Tomato_Outputs/Exps_PS.csv")

Exps_U<-Exps_U %>% 
  mutate(FS = log10(Exposure/413894))

Exps_PS<-Exps_PS %>% 
  mutate(FS = log10(Exposure/81433))

Exps_Binded<-rbind(Exps_U,Exps_PS)



Exps_Binded$Cont<-factor(Exps_Binded$Cont,levels=c("Uniform","Point Source"))
Exps_Binded$Sampling.Point<-factor(Exps_Binded$Sampling.Point,levels=c("Baseline","Preharvest", "Harvest", "Receiving", "Packed Product"))
Exps_Binded$Sampling.Mass<-factor(Exps_Binded$Sampling.Mass,levels=c("2 Tomatoes","6 Tomatoes", "5 X 20 Tomatoes","Baseline"))


Exps_Binded %>%   
  ggplot(aes(x = fct_reorder(Sampling.Point, abs(FS)), y = FS, fill = Sampling.Mass))+
  geom_col(position = "dodge")+
  coord_flip()+
  facet_wrap(~Cont)+
  xlab("Sampling Stage")+
  ylab("Factor Sensitivity log10(Scenario TAC/BAseline TAC)")
  
ggsave(filename=  "Plot Outputs/FS2.png",width = 25, height = 15, units = "cm", dpi = 600)


```

