---
title: "Tomato Model analysis"
author: "Gustavo Reyes"
date: '2022-08-30'
output: html_document
---
```{r}
library(tidyverse)
library(scales)
library(forcats)
```

```{r}
Power_data<-read_csv("Data_Tomato_Outputs/Power_summary.csv")

Power_data$Samp_Plan<-as.factor(Power_data$Samp_Plan)
Power_data$Pick<-as.factor(Power_data$Pick)

Power_data$Samp_Plan<-factor(Power_data$Samp_Plan,levels=c("PH", "HS", "RS", "PPS"))
Power_data$Samp_Mass<-as.factor(Power_data$Samp_Mass)

Power_data %>% 
  ggplot(aes(x = Samp_Plan, y = Power, group = Samp_Mass, shape = Samp_Mass, color = Pick)) +
  geom_point(position=position_dodge(width=0.5))+
  scale_shape_discrete(labels = c("2 Tomatoes", "6 Tomatoes", "100 Tomatoes"), name= "Mass")+
  xlab("Sampling Plan Number")+ ylab ("Sampling Plan Power")

Power_data %>% 
  ggplot(aes(x = Samp_Plan, y = Power,size = Samp_Mass, color = Pick,shape = Pick, group = interaction(Samp_Mass,Pick))) +
  geom_point(stroke = 1.5)+
  geom_line(size = 1,)+
  scale_shape_manual(values = c(15,16,17),name = "Pick")+
  scale_size_manual(values=c(1.5,3,4), name = "Tomatoes Sampled")+
  xlab("Sampling Plan Location")+ ylab ("Sampling Plan Power")+
  scale_y_continuous(n.breaks = 10,labels = scales::percent_format(accuracy = 1))


ggsave(filename=  "Powers.png",width = 25, height = 15, units = "cm", dpi = 600)
```

Main outcomes.
- Higher sampling plan mass yields higher sampling plan power
- Based on contamination scenarios sampling at later picks yoields higher power because contmaination tends to accumulate. 

Contamination at sampling points
```{r}
Cont_data<-read_csv("Data_Tomato_Outputs/Cont_Samp_Point.csv")
Cont_data$Pick<-as.factor(Cont_data$Pick)
Cont_data$Type<-as.factor(Cont_data$Type)
Cont_data$Type<-factor( Cont_data$Type,levels=c("PH", "HS", "RS", "PPS"))

Cont_data %>% 
  ggplot(aes(x = Type, y = Cont, fill = Pick)) +
  geom_boxplot()+
  stat_summary(fun=mean,aes(group=Pick), geom="point", shape=16, size=3, color="red", fill="red",position=position_dodge(.75)) +
  xlab("Sampling Plan")+ ylab ("Total Adulteran Cells (TAC) at sampling point")

ggsave(filename=  "Cont_Sampling_Point.png",width = 25, height = 15, units = "cm", dpi = 600)

Cont_data %>% 
  group_by(Type, Pick) %>% 
  summarize(mean(Cont))
  
```

## Contamination Progression

```{r}
Progression_data<-read_csv("Data_Tomato_Outputs/Cont_Prog.csv")

Progression_data$Plan<-factor(Progression_data$Plan,levels=c("Baseline No Sampling","PH", "HS", "RS", "PPS"))

margin_calc<-function(x){
  margin <- qt(0.975,df=1000-1)*sd(x)/sqrt(1000)
}

Prog_Sum<-Progression_data %>% 
  group_by(Plan,variable, `Plan Mass` ) %>% 
  summarize(mean= mean(value),h95 =mean + margin_calc(value),l95 =mean - margin_calc(value)) 

ggplot(data= Prog_Sum, aes(x= variable,y = mean, group= Plan, color = Plan, fill = Plan))+
  geom_line(size = 1.0, alpha = 1)+
  geom_point(data = Prog_Sum %>% filter(variable == 42), size = 4, alpha = 0.8)+
  #geom_ribbon(aes(ymin = l95, ymax = h95), alpha = 0.05)+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  theme(text = element_text(size=24))+
  scale_y_continuous(trans='log10',labels = trans_format("log10", math_format(10^.x)))+
  labs(y= "Total Adulterant Cells in System", x="Process Stage")+
  facet_wrap(~`Plan Mass`, labeller = labeller(`Plan Mass` = c("A" = "2 tomatoes", "B" = "6 Tomatoes", "C" = "20 X 5 Tomatoes")))
  #ggtitle("1) Random Contamination")+

ggsave(filename=  "PRogression.png",width = 50, height = 25, units = "cm", dpi = 600)

Prog_Sum %>%
  filter(variable ==42 && Plan == "Baseline No Sampling")
###Relative
Prog_Sum %>% 
  filter(variable == 42) %>% 
  mutate(logchange= log10(mean/7245.672	),
         logchange95l = log10(h95/7245.672	),
         logchange95h = log10(l95/7245.672	)
         )


log10(0.4705123/1583.4578) #this to calculate the CI from the paper
log10(65.7962957/1583.4578)
log10(0.4705123/1583.4578) #this to calculate the CI from the paper
log10(199.4115526/1583.4578)

```

