---
title: "Untitled"
author: "Gustavo Reyes"
date: "3/17/2022"
output: html_document
---

```{r}
library(tidyverse)

Gustavo_PS<-read_csv("PointSource.csv")
CPS_1<-read_csv("PointSourceCPS1.csv")

Gustavo_PS$seq<-rep(seq(1,10),500)

GPS_2<-Gustavo_PS %>% 
  group_by(Grabs, seq) %>% 
  summarize( mean_1= mean(Acceptance))%>% 
  group_by(Grabs) %>% 
  summarize(mean_2 = mean(mean_1),q2.5=quantile(mean_1, 0.025), q97.5=quantile(mean_1, 0.975) )



GPS<-Gustavo_PS %>% 
  group_by(Grabs) %>% 
  summarize(mean = mean(Acceptance)) 

CPS<-CPS_1 %>% 
  group_by(param) %>% 
  summarize(mean = mean(Paccept), q2.5 = quantile(Paccept, 0.025), q97.5  = quantile(Paccept, 0.975))



ggplot(data = GPS_2) +
    geom_ribbon(aes(x = Grabs, ymin = q2.5, ymax = q97.5 ), alpha = 0.3)+
    geom_line(aes(x =Grabs , y = mean_2 )) +
    geom_point(aes(x =Grabs , y = mean_2))+
    labs(x = "Number of 3g Sample Point", y = "Probability of acceptance (2.5th - 97.5th percentile)")+
    theme_bw()+
    geom_pointrange(data =CPS,  aes(x=param,y = mean, ymin=q2.5, ymax=q97.5) ,colour="royalblue1", alpha=1, size=0.5, shape = 15)+
  ggtitle("Point Source Contamination: Model Validation") +
  theme(plot.title = element_text(hjust = 0.5))+
  theme(text = element_text(size = 15)) 
    #geom_point(data =CPS,  aes(x=param, y = mean), color = "blue", alpha=0.7, shape = 15)


```


Uniform
```{r}

Gustavo_UN<-read_csv("Uniform_Validation.csv")

Gustavo_UN$seq<-rep(seq(1,10),2000)

CPS_2<-read_csv("CPSUniform.csv")

CPSU<-CPS_2 %>% 
  group_by(param, type) %>% 
  summarize(mean = mean(Paccept), q2.5 = quantile(Paccept, 0.025), q97.5  = quantile(Paccept, 0.975))


GUN<-Gustavo_UN %>% 
  group_by(Cont_Level, Grabs) %>% 
  summarize(mean = mean(Acceptance))

GUN_2<-Gustavo_UN %>% 
  group_by(Grabs,Cont_Level, seq) %>% 
  summarize( mean_1= mean(Acceptance))%>% 
  group_by(Grabs, Cont_Level) %>% 
  summarize(mean_2 = mean(mean_1),q2.5=quantile(mean_1, 0.025), q97.5=quantile(mean_1, 0.975) )


ggplot(data = GUN_2) +
    geom_ribbon(aes(x = Grabs, ymin = q2.5, ymax = q97.5, fill =Cont_Level  ),alpha = 0.3)+
    geom_line(aes(x =Grabs , y = mean_2, color = Cont_Level ),size = 0.8) +
    geom_point(aes(x =Grabs , y = mean_2,color = Cont_Level), size = 2.5)+
    labs(x = "Number of 3g Sample Point", y = "Probability of acceptance (2.5th - 97.5th percentile)")+
    theme_bw()+
  geom_pointrange(data =CPSU,  aes(x=param,y = mean, ymin=q2.5, ymax=q97.5 ) ,color ="royalblue1"  , alpha=0.8, size=0.5, shape = 15)+
  ggtitle("Uniform Contamination: Model Validation") +
  theme(plot.title = element_text(hjust = 0.5))+
  theme(text = element_text(size = 15))    


```

