---
title: "R Plots"
author: "Gustavo Reyes"
date: '2022-05-03'
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(ggplot2)
library(scales)

#setwd("C:/Users/Gustavo Reyes/Box/CPS Project- Farm to Facility/Papers/CSV Data")
setwd("C:/Users/gareyes3/Box Sync/CPS Project- Farm to Facility/Papers/CSV Data")
```



## Factor Sensitivity plot

```{r}
FSdf<-read_csv("FSdf.csv")

log10(4388/13740302)

FSdf$FS<-c(0,-1.2769679063, -1.7998346791, -0.8368652945, -0.0747038970, -1.2406815098, 0.0373676179, -0.0048823063, -0.1545419933, -0.5291657397, -0.0500426243, -0.1400479579, -0.1535739862, -0.0009942127,-3.492672, -3.516924,-3.497117, -3.597166, -3.495334, -3.500707, -3.499108, -3.49573)
```

```{r}
order_x = c("Baseline-NI",
            "Baseline-NI-Washing",
            "Baseline-NI-Washing 10 ppm",
            "Baseline-NI Holding",
            "Baseline-NI Pre-cooling", 
            "Baseline-NI PreWash",
            "Baseline-NI Sanitation", 
            "Baseline-NI PHS4d",
            "Baseline-NI PHS4h",
            "Baseline-NI Int",
            "Baseline-NI HS", 
            "Baseline-NI RS",
            "Baseline-NI FPS", 
            "Baseline-NI CS", 
            "Baseline-AI",
            "Baseline-AI PHS4d",
            "Baseline-AI PHS4h", 
            "Baseline-AI PHSInt", 
            "Baseline-AI HS",
            "Baseline-AI RS", 
            "Baseline-AI FPS", 
            "Baseline-AI CS")

labels_x = c("Baseline-NI" = "Baseline",
            "Baseline-NI-Washing" = "Washing",
            "Baseline-NI-Washing 10 ppm" = "Washing 10 ppm",
            "Baseline-NI Holding" ="Holding",
            "Baseline-NI Pre-cooling" = "Pre-Cooling", 
            "Baseline-NI PreWash" = "Pre-Wash",
            "Baseline-NI Sanitation" = "Sanitation", 
            "Baseline-NI PHS4d" = "PHS 4d",
            "Baseline-NI PHS4h"="PHS 4h",
            "Baseline-NI Int" = "PHS Int",
            "Baseline-NI HS" = "HS", 
            "Baseline-NI RS" = "RS",
            "Baseline-NI FPS" = "FPS", 
            "Baseline-NI CS" = "CS", 
            "Baseline-AI"= "All Interventions",
            "Baseline-AI PHS4d" = "PHS 4d",
            "Baseline-AI PHS4h"="PHS 4h", 
            "Baseline-AI PHSInt" = "PHS Int", 
            "Baseline-AI HS"= "HS",
            "Baseline-AI RS" = "RS", 
            "Baseline-AI FPS" = "FPS", 
            "Baseline-AI CS" = "CS")



FSdf$System<-c(rep("No Intervention", 14),rep("All Interventions", 8))

pfs = ggplot(data= FSdf, aes(x = fct_reorder(Name, abs(FS)), y = FS, fill = System))+
  geom_col()+
  coord_flip()


  pfs+
  theme(text = element_text(size=24))+
  geom_hline(yintercept = -3.492672,linetype="dotted", size = 2)+
    geom_hline(yintercept = 0,linetype="dashed",size = 2)+
  ylab("Factor Sensitivity Index")+
  xlab("Scenario/ Intervention")+
  scale_x_discrete(labels = labels_x)+
  theme(text = element_text(size=26), axis.text = element_text(size = 26))+
  theme(legend.text=element_text(size=20),legend.title=element_text(size=20))+
  #scale_x_discrete(limits=rev)+
  ggtitle("Factor Sensitivity Analysis (FS)")

  ggsave("FS.png", width = 40, height = 30, units = "cm", dpi = 600)


```


## Contmainationation progression
```{r}
NI_1_ProgInt<-read_csv("Melted_Prog_DF_NI_1.csv")
NI_2_ProgInt<-read_csv("Melted_Prog_DF_NI_2.csv")
NI_3_ProgInt<-read_csv("Melted_Prog_DF_NI_3.csv")

order_progression<-unique(NI_1_ProgInt$variable) #getting exact order of events

margin_calc<-function(x){
  margin <- qt(0.975,df=1000-1)*sd(x)/sqrt(1000)
}

#random
NI_Summ<-NI_1_ProgInt %>% 
  group_by(Type,variable ) %>% 
  summarize(mean= mean(value),h95 =mean + margin_calc(value),l95 =mean - margin_calc(value)) %>% 
  mutate(ContScen = "Random Contamination") %>% 
  drop_na()
#10%
NI_Summ_3<-NI_3_ProgInt %>% 
  group_by(Type,variable ) %>% 
  summarize(mean= mean(value),h95 =mean + margin_calc(value),l95 =mean - margin_calc(value)) %>% 
  mutate(ContScen = "10% Clustered Contamaination") %>% 
  drop_na()
#1%
NI_Summ_2<-NI_2_ProgInt %>% 
  group_by(Type,variable ) %>% 
  summarize(mean= mean(value),h95 =mean + margin_calc(value),l95 =mean - margin_calc(value)) %>% 
    mutate(ContScen = "1% Clustered Contamaination") %>% 
  drop_na()

Binded_all<-bind_rows(NI_Summ,NI_Summ_3,NI_Summ_2)


Binded_all$variable<-factor(Binded_all$variable, levels=order_progression)
Binded_all$ContScen<-factor(Binded_all$ContScen, levels=c("Random Contamination","10% Clustered Contamaination","1% Clustered Contamaination"))


ggplot(data= Binded_all, aes(x= variable,y = mean, group= Type, color = Type, linetype=Type, fill = Type))+
  geom_line(size = 0.75)+
  geom_ribbon(aes(ymin = l95, ymax = h95), alpha = 0.2)+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  theme(text = element_text(size=24))+
   scale_y_continuous(trans='log10',
                      labels = trans_format("log10", math_format(10^.x)))+
  labs(y= "Total CFUs in System", x="Process Stage")+
  #ggtitle("1) Random Contamination")+
  facet_wrap(~ ContScen, ncol = 2)

ggsave("contprog.png", width = 40, height = 35, units = "cm", dpi = 600)
  



#Making Individual One. 

```


## Contamination at sampling Point

```{r}
Con_S<-read_csv("ContSamp.csv")
Con_S_AI<-read_csv("ContSamp_AI.csv")

Con_S$Process<-"No Intervetion"
Con_S_AI$Process<-"All Interventions"

####
Con_S %>% 
  group_by(variable) %>% 
  summarise(mean(value), quantile(value, 0.05), quantile(value, 0.95))
  
Con_S_AI %>% 
  group_by(variable) %>% 
  summarise(mean(value), quantile(value, 0.05), quantile(value, 0.95))

Binded_Con<-bind_rows(Con_S,Con_S_AI)


Order_ConS<-unique(Con_S$variable)
Binded_Con$variable<-factor(Binded_Con$variable, levels=Order_ConS)
Binded_Con$`Cont Scenario`<-factor(Binded_Con$`Cont Scenario`, levels=c("Random","10% Cluster","1% Cluster"))

Binded_Con %>% 
  group_by(variable,`Cont Scenario` ) %>% 
  summarise(quantile = quantile(value, 0.05))


ggplot(data = Binded_Con, aes(x = variable, y =value, fill = `Cont Scenario`))+
  geom_boxplot()+
   scale_y_continuous(trans='log10',
                      labels = trans_format("log10", math_format(10^.x)))+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  theme(text = element_text(size=24))+
  labs(x= "Sampling Step", y = "Total CFUs in System")+
  facet_wrap(~Process)

ggsave("Cont_Sampling.png", width = 40, height = 35, units = "cm", dpi = 600)

options("device")

log10( 4447 /13749302 )

(1-(4447 /13749302))*100

```


## Poster Plot Scenario Comparison

```{r}
order_x2 = c('BaselineNI',
 'PHS4D_NI',
 'PHS4H_NI',
 'PHSInt_NI',
 'HTrad_NI',
 'RSTrad_NI',
 'FPSTrad_NI',
 'CS_NI',
 'BaselineAI',
 'PHS4D_AI',
 'PHS4H_AI',
 'PHSInt_AI',
 'HTrad_AI',
 'RSTrad_AI',
 'FPSTrad_AI',
 'CS_AI')

labels_2 = c('BaselineNI' = "Baseline",
 'PHS4D_NI'= "PHS 4d",
 'PHS4H_NI'= "PHS 4h",
 'PHSInt_NI'= "PHS Int",
 'HTrad_NI'= "HS",
 'RSTrad_NI'= "RS",
 'FPSTrad_NI'= "FPS",
 'CS_NI'= "CS",
 'BaselineAI'= "Baseline",
 'PHS4D_AI'= "PHS 4d",
 'PHS4H_AI'= "PHS 4h",
 'PHSInt_AI'= "PHS Int",
 'HTrad_AI'= "HS",
 'RSTrad_AI'= "RS",
 'FPSTrad_AI'= "FPS",
 'CS_AI'= "CS")




Final_Exps<-read_csv("final_exp.csv")
empty<-c()
list_loop<-c(1,9,17,25,33,41)
for (i in list_loop ){
  list_2<-Final_Exps$Expossure[i:(i+7)]/Final_Exps$Expossure[i]
  empty<-c(empty,list_2 )
}

Final_Exps$`Relative Difference`<-empty

Final_Exps[48,6] = 0.999999
Final_Exps[32,6] = 0.999999

Final_Exps$`Sampling Plan`<-factor(Final_Exps$`Sampling Plan`, levels = order_x2)
Final_Exps$`Cont Scenario`<-factor(Final_Exps$`Cont Scenario`, levels = c("Random Contamination", "10% Cluster Contamination",  "1% Cluster Contamination"))

ggplot(data= Final_Exps, aes(x =fct_reorder(`Sampling Plan`, `Relative Difference`) , y = `Relative Difference`, fill =`Cont Scenario` ))+
  geom_col(position = "dodge")+
  coord_flip()+
  theme(text = element_text(size=26), axis.text = element_text(size = 24))+
  theme(legend.text=element_text(size=16),legend.title=element_text(size=20))+
  geom_hline(yintercept = 1,linetype="dashed",size = 2)+
  labs(x= "Sampling Plan", y= "Relative Difference: Total Consumer Exposure")+
  facet_wrap(.~ `Baseline System`, scales = "free")+
  theme(legend.position = 'top', 
        legend.spacing.x = unit(1.0, 'cm'))+
  scale_x_discrete(labels = labels_2)+
  scale_y_continuous(labels = scales::percent)
  #geom_hline(yintercept = 13740302,linetype="dotted")+
  #geom_hline(yintercept = 4532,linetype="dashed")
  ggsave("EXposure.png", width = 40, height = 28, units = "cm", dpi = 600)
```


